---
containers:
  - name: synthetics-check-runner
    image: 'datadog/synthetics-private-location-worker:1.74.0@sha256:0033af326ed58434cec2e505e41c56560218ed338974fe8d2392a3f9d2bb2385'
    pull: yes
    networks:
      - name: "monitoring"
