---
containers:
  - name: synthetics-check-runner
    image: 'datadog/synthetics-private-location-worker:1.73.0@sha256:781e73792b78c6e3d6efb50a187ffe28a11a2015030c6bc7799d7156869dbd29'
    pull: yes
    networks:
      - name: "monitoring"
